# -*- coding: utf-8 -*-
"""Week3_Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDguwAE77T1UYuEujg-O11nJsl3G8CYI

Part A: Understanding the Dataset
"""

#Q1. Dataset Overview
import pandas as pd
data = pd.read_csv('/agriculture_yield_dataset.csv')
print("rows|cols")
data.shape # number of rows and columns

print('\nColumns:') #column names
print(data.columns)

data.head(10) #first 10 rows

#Q2. Data Types and Missing Values
data.dtypes #Check the data type of each column.

#Identify whether any missing values are present.
print(data.isna().sum())

#If missing values exist, mention the affected columns.
data.isnull().any()
data.isna().any()

#Q3. Descriptive Statistics
#Which feature has the highest mean value?
highest_mean_feature = data.mean(numeric_only=True).idxmax()
print(highest_mean_feature)

#Which feature has the highest standard deviation?
max_std_feature = data.std(numeric_only=True).idxmax()
print(max_std_feature)

"""Part B: Exploratory Data Analysis (EDA)"""

#Q4. Distribution Analysis
# Create histograms for:
# rainfall_mm

import matplotlib.pyplot as plt

plt.hist(data["rainfall_mm"])
plt.xlabel('Rainfall (mm)')
plt.ylabel('Frequency')
plt.title('Histogram of Rainfall')
plt.show()

"""Observations:
1) Lowest ever rainfall was of the range 400mm.
2) 400mm rainfall occured least frequently at a frequency of 130.
"""

#temperature_c
plt.hist(data["temperature_c"])
plt.xlabel('Temperature (C)')
plt.ylabel('Frequency')
plt.title('Histogram of Temperature')
plt.show()

"""Observations:
1) The least frequent temperature was 35 Centigrade, with a frequency of almost 120.
2) The most frequent temperature was 25 Centigrade, with a frequency of 160.
"""

#fertilizer_kg
plt.hist(data["fertilizer_kg"])
plt.xlabel('Fertilizer (kg)')
plt.ylabel('Frequency')
plt.title('Histogram of Fertilizer')
plt.show()

"""Observations:
1) The most frequent use of fertilizer is 75kg, with a frequency of 175.
2) The least frequent is usage 150-175 kg with a freqency of 125.
"""

#yield_ton_per_hectare
plt.hist(data["yield_ton_per_hectare"])
plt.xlabel('Yield (ton/ha)')
plt.ylabel('Frequency')
plt.title('Histogram of Yield')
plt.show()

"""Observations:
1) The most frequent yield is 4.5 ton per ha, with a frequency of 350.
2) The least frequent is a yield of 7,5 ton per ha.
"""

#Q5. Crop Type Analysis
#Find the number of records for each crop type.
data['crop_type'].value_counts()

#Create a count plot (bar chart) for crop_type

counts = data['crop_type'].value_counts()

plt.bar(counts.index, counts.values, color='skyblue', width=0.6)
plt.xlabel('Crop Type')
plt.ylabel('Count')
plt.title('Distribution of Crop Types')
plt.show()

#Which crop appears most frequently?
frequent_crop = data['crop_type'].value_counts().idxmax()
print(frequent_crop)

#Q6. Soil Type Analysis
# Find the frequency of each soil type.
data['soil_type'].value_counts()

#Create a count plot for soil_type.
counts = data['soil_type'].value_counts()

plt.bar(counts.index, counts.values, color='skyblue', width=0.6)
plt.xlabel('Soil Type')
plt.ylabel('Count')
plt.title('Distribution of Soil Types')
plt.show()

#Which soil type is most common?
most_common_soil = data['soil_type'].value_counts().idxmax()
print(most_common_soil)

#Q7. Yield Distribution
#Create a histogram of yield_ton_per_hectare.
plt.hist(data["yield_ton_per_hectare"])
plt.xlabel('Yield (ton/ha)')
plt.ylabel('Frequency')
plt.title('Histogram of Yield')
plt.show()

"""Q. Is the distribution approximately normal?  

A. Yes, it is approximately normal

Q. Are there any noticeable outliers?

A. No, there aren't any extreme outliers.
"""

#Q8. Scatter Plot Analysis
#Create scatter plots of:
#1. rainfall_mm vs yield_ton_per_hectare
plt.scatter(data["rainfall_mm"], data["yield_ton_per_hectare"])
plt.xlabel('Rainfall (mm)')
plt.ylabel('Yield (ton/ha)')
plt.title('Rainfall vs Yield')
plt.show()

#2. fertilizer_kg vs yield_ton_per_hectare
plt.scatter(data["fertilizer_kg"], data["yield_ton_per_hectare"])
plt.xlabel('Fertilizer (kg)')
plt.ylabel('Yield (ton/ha)')
plt.title('Fertilizer vs Yield')
plt.show()

"""Based on the plots:

Q. Which feature appears to have a stronger relationship with yield?

A. Rainfall appears to have a strong correlation with overall yield.
"""

#Q9. Correlation Analysis
#Generate a correlation matrix for numerical features.

numerical_data = data.select_dtypes(include='number')

correlation_matrix = numerical_data.corr()

print(correlation_matrix)

#Create a heatmap.
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Matrix')
plt.show()

#Identify the top three features most correlated with crop yield.
correlation_matrix = data.corr(numeric_only=True)

yield_corr = correlation_matrix['yield_ton_per_hectare']

yield_corr = yield_corr.drop('yield_ton_per_hectare')

top_3 = yield_corr.abs().sort_values(ascending=False).head(3)

print(top_3)

#Q10. Group-Based Analysis
#Calculate the average yield for:
#Each crop type
avg_yield_crop = data.groupby('crop_type')['yield_ton_per_hectare'].mean()

print(avg_yield_crop)
print(avg_yield_crop.idxmax())

#Each soil type
avg_yield_soil = data.groupby('soil_type')['yield_ton_per_hectare'].mean()

print(avg_yield_soil)
print(avg_yield_soil.idxmax())

"""Q. Which crop and soil type have the highest average yield?

A. Rice has the highest crop yield and Loamy soil has the highest soil yield.

Part C: Data Preparation
"""

#Q11. Feature Encoding

#Identify the categorical columns.

categorical_cols = data.select_dtypes(include='object').columns

print("Categorical columns:")
print(categorical_cols)

#Convert them into numerical form using One-Hot Encoding.
data_encoded = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

#Display the first five rows of the transformed dataset.
print(data_encoded.head())

#Q12. Feature Selection
y = data_encoded['yield_ton_per_hectare']
X = data_encoded.drop('yield_ton_per_hectare', axis=1)
print("Target variable:", y.name)

"""Part D: Machine Learning"""

#Q13. Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

#Q14. Linear Regression Model
#Train a Linear Regression model.
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

#Display the model coefficients and intercept.

print("Intercept:")
print(model.intercept_)

print("\nCoefficients:")
print(model.coef_)
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

print(coefficients)

#Which feature has the highest positive coefficient?

highest_feature = coefficients.loc[
    coefficients['Coefficient'].idxmax()
]

print("Feature with highest positive coefficient:")
print(highest_feature)