# -*- coding: utf-8 -*-
"""Week_4_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRMJ_aniBg_oYjirjGT6t1sLpO60WnqO

Ashita Sharma 04101172025

Question 1. Load the Loan Prediction dataset and perform an initial analysis.
Tasks:
1. Display the first 10 records.
2. Identify all features and the target variable.
3. Determine the number of records and attributes.
4. Check for missing values.
5. Describe the statistical properties of numerical features.
"""

import pandas as pd
#1.
data = pd.read_csv('loan_prediction.csv')
data.head(10)

#2.
m_data = data.drop('Loan_ID', axis=1)
target_var = m_data['Loan_Status']
features = m_data.drop('Loan_Status', axis=1)
print(target_var)
print(features)

#3.
data.shape

#4.
m_data.isna().sum()

#5.
m_data.describe()

"""Question 2. Perform data preprocessing.
Tasks:
1. Handle missing values using appropriate techniques.
2. Convert categorical variables into numerical format.
3. Normalize or standardize numerical features (if required).
4. Create the final feature matrix and target variable.

"""

#1.
data_cleaned = m_data.dropna()
data_cleaned.shape

#2.
x = data_cleaned.drop('Loan_Status', axis=1)
y = data_cleaned['Loan_Status']
x_encoded = pd.get_dummies(
    x,
    columns=['Gender', 'Married', 'Education', 'Self_Employed'],
    dtype=int
)
y_encoded = y.map({'N': 0, 'Y': 1})
area_map = {'Rural': 1, 'Semiurban': 2, 'Urban': 3}
x_encoded['Property_Area'] = x_encoded['Property_Area'].map(area_map)
x_encoded['Dependents'] = x_encoded['Dependents'].replace('3+', 3)
x_encoded['Dependents'] = x_encoded['Dependents'].astype(int)
print(x_encoded.dtypes)

#3.
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x_encoded)

#4.
print(x_encoded.head())

"""Question 3. Perform exploratory data analysis to understand factors affecting loan approval.
Create at least five visualizations, such as:
1. Loan approval distribution.
2. Applicant income vs loan approval.
3. Credit history vs loan approval.
4. Education level vs loan approval.
5. Property area vs loan approval.

"""

#1.
import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Loan_Status', data=data_cleaned)
plt.title("Loan Approval Distribution")
plt.show()

#2.
sns.boxplot(x='Loan_Status', y='ApplicantIncome', data=data_cleaned)
plt.title("Applicant Income vs Loan Approval")
plt.show()

#3.
sns.countplot(x='Credit_History', hue='Loan_Status', data=data_cleaned)
plt.title("Credit History vs Loan Approval")
plt.show()

#4.
sns.countplot(x='Education', hue='Loan_Status', data=data_cleaned)
plt.title("Education Level vs Loan Approval")
plt.show()

#5.
sns.countplot(x='Property_Area', hue='Loan_Status', data=data_cleaned)
plt.title("Property Area vs Loan Approval")
plt.show()

"""1. Which feature appears most influential in loan approval?
A: Credit history
2. What patterns can be observed from the visualizations?
Graduated, urban/semiurban applicants with a good credit history get loans approved quicker

Question 4. Split the dataset into training and testing sets (80:20).
Train the following models:
1. Logistic Regression
2. Decision Tree Classifier
3. Random Forest Classifier
For each model: Calculate Accuracy, Precision, Recall, F1 Score. Present the results in a comparison table.
"""

import pandas as pd

X = pd.get_dummies(data_cleaned.drop('Loan_Status', axis=1), drop_first=True)
y = data_cleaned['Loan_Status'].map({'N': 0, 'Y': 1})

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Models
lr = LogisticRegression(max_iter=1000)
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)

# Train
lr.fit(X_train, y_train)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
y_pred_dt = dt.predict(X_test)
y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(y_true, y_pred):
    return [
        accuracy_score(y_true, y_pred),
        precision_score(y_true, y_pred),
        recall_score(y_true, y_pred),
        f1_score(y_true, y_pred)
    ]

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree", "Random Forest"],
    "Accuracy": [
        evaluate_model(y_test, y_pred_lr)[0],
        evaluate_model(y_test, y_pred_dt)[0],
        evaluate_model(y_test, y_pred_rf)[0]
    ],
    "Precision": [
        evaluate_model(y_test, y_pred_lr)[1],
        evaluate_model(y_test, y_pred_dt)[1],
        evaluate_model(y_test, y_pred_rf)[1]
    ],
    "Recall": [
        evaluate_model(y_test, y_pred_lr)[2],
        evaluate_model(y_test, y_pred_dt)[2],
        evaluate_model(y_test, y_pred_rf)[2]
    ],
    "F1 Score": [
        evaluate_model(y_test, y_pred_lr)[3],
        evaluate_model(y_test, y_pred_dt)[3],
        evaluate_model(y_test, y_pred_rf)[3]
    ]
})

print(results)

"""Question 5. Based on the performance metrics:
1. Identify the best-performing model.
A: Logistic Regression
2. Justify your choice using evaluation metrics.
A: It has a high accuracy, recall and F1 score.
3. Discuss the strengths and limitations of each model.
A: Logistic regression is simple and fast to train but can easily struggle in non-linear patterns
Decision Tree is easy to understand and visualize but is very prone to overfitting and generally has a lower accuracy overall.
Random Forest is more accurate than a decision tree and is able to handle non-linear relations but is slower to train as well as computationally heavy.

Question 6. Apply Stratified 5-Fold Cross Validation to all three models.
Tasks:
1. Compute accuracy for each fold.
2. Calculate mean accuracy and standard deviation.
3. Compare cross-validation results with the train-test split results.
"""

from sklearn.model_selection import StratifiedKFold, cross_val_score
import numpy as np
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr_scores = cross_val_score(lr, X, y, cv=skf, scoring='accuracy')

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt_scores = cross_val_score(dt, X, y, cv=skf, scoring='accuracy')

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf_scores = cross_val_score(rf, X, y, cv=skf, scoring='accuracy')

print("Logistic Regression fold accuracies:", lr_scores)
print("Decision Tree fold accuracies:", dt_scores)
print("Random Forest fold accuracies:", rf_scores)

results_cv = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree", "Random Forest"],
    "Mean Accuracy": [
        lr_scores.mean(),
        dt_scores.mean(),
        rf_scores.mean()
    ],
    "Std Deviation": [
        lr_scores.std(),
        dt_scores.std(),
        rf_scores.std()
    ]
})

print(results_cv)

"""1. Why is Stratified K-Fold preferred for this dataset?
A: Usually, loan datasets are imbalanced, e.g, some might have a lot of disapprovals but not a lot of approvals. Thus, the model can become unreliable due to biased training. Stratified k-fold prevents that.
2. Which model shows the most consistent performance?
The model with the most consistent performance is the model with a high accuracy as well as a low standard deviation. Here, the best performing model is the Logistic Regression.

Question 7. Perform hyperparameter tuning on the Random Forest Classifier using GridSearchCV. Tune the following parameters:
n_estimators = [50, 100, 200]
max_depth = [3, 5, 10]
min_samples_split = [2, 5, 10]
Tasks:
1. Identify the best parameter combination.
2. Report the best cross-validation score.
3. Evaluate the tuned model on the test set.
Compare:
Model performance before tuning
Model performance after tuning
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report
rf = RandomForestClassifier(random_state=42)

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 10],
    'min_samples_split': [2, 5, 10]
}

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)
print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

best_rf = grid_search.best_estimator_

y_pred_tuned = best_rf.predict(X_test)
tuned_accuracy = accuracy_score(y_test, y_pred_tuned)

print("Tuned Random Forest Accuracy:", tuned_accuracy)
print(classification_report(y_test, y_pred_tuned))

before_tuning = 0.7917  # replace with your actual value
after_tuning = tuned_accuracy

print("Before Tuning Accuracy:", before_tuning)
print("After Tuning Accuracy:", after_tuning)

"""Tasks:
1. Identify the best parameter combination.

A: 'max_depth': 3, 'min_samples_split': 5, 'n_estimators': 200

2. Report the best cross-validation score.
0.802
3. Evaluate the tuned model on the test set.
After tuning the accuracy increased by 2%.
Compare:
Model performance before tuning
Model performance after tuning

Before tuning, the accuracy was 79%, which is decent. However, after tuning, the accuracy was boosted to 81%.

Question 8. Train three Decision Tree models using:
max_depth = 2
max_depth = 5
max_depth = 15
For each model:
1. Compute training accuracy.
2. Compute testing accuracy.
3. Compare the results.
Answer:
1. Which model exhibits underfitting?
2. Which model exhibits overfitting?
3. Which model provides the best balance between bias and variance?
Present your findings in a table.
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

models = {
    "Depth 2": DecisionTreeClassifier(max_depth=2, random_state=42),
    "Depth 5": DecisionTreeClassifier(max_depth=5, random_state=42),
    "Depth 15": DecisionTreeClassifier(max_depth=15, random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_acc = accuracy_score(y_train, train_pred)
    test_acc = accuracy_score(y_test, test_pred)

    results.append([name, train_acc, test_acc])

import pandas as pd

results_df = pd.DataFrame(
    results,
    columns=["Model", "Training Accuracy", "Testing Accuracy"]
)

print(results_df)

"""The underfitted data is depth 2, with a low training accuracy and a similar testing accuracy as the others. Depth 15 is overfitted as it performs great on training data but fails with testing data."""